#系统自动配置    
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    host: 192.168.2.188
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${nk.mysqldb.url} #jdbc:mysql://192.168.2.188:3306/live?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  rabbitmq:
    host: 192.168.2.188
    post: 52765
    username: guest
    password: guest
mybatis:
  type-aliases-package: com.core.model
#日志文件配置
logging:
  config: classpath:config/logging-config.xml
  #path: /var/stslogs
server:
  tomcat:
    uri-encoding: UTF-8
 
#应用级配置
nk: 
  www: 
    domain: drnaoku.com
    port: 80
    http: http://${nk.www.domain}:${nk.www.port}
  auth: 
    id: route
    secret: token
    tokenUrl: ${nk.www.http}/api/auth/oauth/token
    authorizeUrl: ${nk.www.http}/api/auth/oauth/authorize
    checkUrl: ${nk.www.http}/api/auth/oauth/check_token
    userUrl: ${nk.www.http}/api/auth/user
  mysqldb: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.188:3306/live?useUnicode=true&characterEncoding=utf-8
    neturl: jdbc:mysql://testnaoku.cn:23306/live?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 192.168.2.188
    port: 6379
  rabbitmq:
    host: 192.168.2.188
    post: 6379
    username: guest
    password: guest
  upload: 
    path: e://liveupload
